### ISSUE TITLE
Error in running bash in Windows 11 (PyCharm)

### ISSUE THREAD

**Issue by skillcodex-official** [saifhassan/Wav2Lip-HD#16]
I have Numpy 

(pythonVenv) PS F:\wav2lip\Wav2Lip-HD> bash run_final.sh          
Traceback (most recent call last):
  File "inference.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
  File "video2frames.py", line 36
    frame_file = os.path.join(frame_folder, f'frame_{frame_index:05d}.jpg')
                                                                         ^
SyntaxError: invalid syntax
  File "inference_realesrgan.py", line 159
    save_path = os.path.join(args.output, f'{imgname}.{extension}')
                                                                 ^
SyntaxError: invalid syntax

**Comment by start-life** [comment]
How can you run it in Windows?
