### ISSUE TITLE
Error when installing dependencies with "pip install -r requirements.txt" on Mac + python 3.12

### ISSUE THREAD

**Issue by mcohoon04** [saifhassan/Wav2Lip-HD#44]
When attempting to install requirements I get the below error installing numba. I tried ensuring the numba and numpy versions were compatable but that didnt help and I tried deleting and remaking environment. any ideas?
 
The Error Message:
 
error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-install-ug318los/numpy_4167148486ec44729b47c5da97b7f7ca/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-install-ug318los/numpy_4167148486ec44729b47c5da97b7f7ca/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-install-ug318los/numpy_4167148486ec44729b47c5da97b7f7ca/tools/cythonize.py", line 238, in <module>
          main()
        File "/private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-install-ug318los/numpy_4167148486ec44729b47c5da97b7f7ca/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-install-ug318los/numpy_4167148486ec44729b47c5da97b7f7ca/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-install-ug318los/numpy_4167148486ec44729b47c5da97b7f7ca/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-install-ug318los/numpy_4167148486ec44729b47c5da97b7f7ca/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/marcus/Wav2Lip-HD/.venv/bin/python3.12', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/marcus/Wav2Lip-HD/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/marcus/Wav2Lip-HD/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/marcus/Wav2Lip-HD/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-build-env-152p9k6_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-build-env-152p9k6_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/6v/v1kbh6v178df_lj294zz2scc0000gp/T/pip-build-env-152p9k6_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by vishal24102002** [comment]
try using lower python versions for this projects

**Comment by taresh18** [comment]
Use python=3.8
